### ISSUE TITLE
Not a Valid Directory

### ISSUE THREAD

**Issue by enessol** [harisreedhar/DeOldify#1]
Hi, I have tried to run your command but I get this error:
**AssertionError: dummy is not a valid directory.**

How can I solve this problem?

**Comment by harisreedhar** [comment]
@enessol Can you show full error log?

**Comment by enessol** [comment]
@harisreedhar Thank you for your reply, I managed to run it with help from a Github user. However, I have another issue that is not that important but if you know the solution please let me know :) After I run your script it colores the video. However, the output does not contain audio. And displays the following error on cmd.

Transferring audio
Traceback (most recent call last):
File "\DeOldify-master\run_local.py", line 137, in
model.colorize_video(args)
File "\DeOldify-master\run_local.py", line 101, in colorize_video
subprocess.call(" && ".join([command1, command2]), shell=platform.system() != 'Windows')
File "\anaconda3\lib\subprocess.py", line 349, in call
with Popen(*popenargs, **kwargs) as p:
File "anaconda3\lib\subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "anaconda3\lib\subprocess.py", line 1420, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find file specified
